# Thay YOUR-USERNAME báº±ng username GitHub cá»§a báº¡n
baseURL = 'https://Haihihihihu.github.io/my-blog/'
languageCode = 'vi'
title = 'Blog Há»c Táº­p & Chia Sáº»'
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
defaultTheme = "dark"
ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = true

  [params.profileMode]
  enabled = true
  title = "Xin chÃ o má»i ngÆ°á»i, mÃ¬nh lÃ  Háº£i"
  subtitle = "Sinh viÃªn chuyÃªn ngÃ nh An ninh máº¡ng, vÃ  Ä‘Ã¢y lÃ  khÃ´ng gian mÃ¬nh dÃ¹ng Ä‘á»ƒ ghi chÃ©p vÃ  chia sáº» nhá»¯ng gÃ¬ mÃ¬nh há»c Ä‘Æ°á»£c vá» Láº­p trÃ¬nh máº¡ng, Java vÃ  JavaScript. Blog nÃ y khÃ´ng chá»‰ lÃ  Ä‘á»“ Ã¡n mÃ´n há»c mÃ  cÃ²n lÃ  hÃ nh trÃ¬nh khÃ¡m phÃ¡ tháº¿ giá»›i cÃ´ng nghá»‡ cá»§a má»™t ngÆ°á»i Ä‘ang ngÃ y cÃ ng yÃªu thÃ­ch láº­p trÃ¬nh hÆ¡n. Hy vá»ng nhá»¯ng kiáº¿n thá»©c mÃ¬nh chia sáº» sáº½ há»¯u Ã­ch cho cÃ¡c báº¡n cÃ¹ng Ä‘am mÃª!"
  imageUrl = "avatar.png"
  imageWidth = 150
  imageHeight = 150
  imageTitle = "Háº£i"
  
    [[params.profileMode.buttons]]
    name = "ğŸ“ BÃ i viáº¿t"
    url = "posts"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/Haihihihihu"
  
  [[params.socialIcons]]
  name = "email"
  url = "mailto:phamhai0959@gmail.com"
  
  [[params.socialIcons]]
  name = "phone"
  url = "tel:0396993820"
  

[[menu.main]]
name = "Trang chá»§"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Dá»± Ã¡n"
identifier = "projects"
url = "/projects/"
weight = 3

[[menu.main]]
name = "ğŸ¯ Main Projects"
parent = "projects"
url = "/projects/#main"
weight = 1

[[menu.main]]
name = "ğŸ’¡ Side Projects"
parent = "projects"
url = "/projects/#side"
weight = 2

[[menu.main]]
name = "Vá» tÃ´i"
url = "/about/"
weight = 4
